# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SparkyCli < Formula
  desc "CLI for SparkyFitness - log food, exercise, and biometrics from your terminal"
  homepage "https://github.com/aronjanosch/sparky-cli"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aronjanosch/sparky-cli/releases/download/v0.2.7/sparky_0.2.7_darwin_amd64.tar.gz"
      sha256 "9707683d48586ea3674a10d038ea0b76f6877ba58c6b873a5a42a9f4927b1037"

      define_method(:install) do
        bin.install "sparky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aronjanosch/sparky-cli/releases/download/v0.2.7/sparky_0.2.7_darwin_arm64.tar.gz"
      sha256 "f4fe299f7204be404440665b18157cb71eb19a9ddc56308920f123436b346dc9"

      define_method(:install) do
        bin.install "sparky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aronjanosch/sparky-cli/releases/download/v0.2.7/sparky_0.2.7_linux_amd64.tar.gz"
      sha256 "0850fa518f33217c40af1b21ecbe24c0f1d9f1c527beb2e9a5da81ecb81d5b2f"
      define_method(:install) do
        bin.install "sparky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aronjanosch/sparky-cli/releases/download/v0.2.7/sparky_0.2.7_linux_arm64.tar.gz"
      sha256 "9f3c20a4a4265cb7d1b96c22bec81ebb8cb09f962d5428f4f42e7e0e021916c9"
      define_method(:install) do
        bin.install "sparky"
      end
    end
  end

  test do
    system "#{bin}/sparky", "--version"
  end
end
