# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmxCli < Formula
  desc "Thermomix/Cookidoo CLI — meal plans, recipe search, and shopping lists from your terminal"
  homepage "https://github.com/aronjanosch/tmx-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.2.0/tmx_0.2.0_darwin_amd64.tar.gz"
      sha256 "b094696130990e5a53ad703c23484ad86010212eceba6e4f6bf593ba95fdfedc"

      define_method(:install) do
        bin.install "tmx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.2.0/tmx_0.2.0_darwin_arm64.tar.gz"
      sha256 "7fcb7dccb86923271dffcba67297a06d4fb1134c6373b039f33400a401731813"

      define_method(:install) do
        bin.install "tmx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.2.0/tmx_0.2.0_linux_amd64.tar.gz"
      sha256 "2e22e40810486b8cf39cfce714307ffe51925958873dcdb8404a9bcca23d151c"
      define_method(:install) do
        bin.install "tmx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.2.0/tmx_0.2.0_linux_arm64.tar.gz"
      sha256 "d49a67a397efb1366ff968be155c3c8bb983e67224122e1220acf60130988217"
      define_method(:install) do
        bin.install "tmx"
      end
    end
  end

  test do
    system "#{bin}/tmx", "--version"
  end
end
