# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmxCli < Formula
  desc "Thermomix/Cookidoo CLI — meal plans, recipe search, and shopping lists from your terminal"
  homepage "https://github.com/aronjanosch/tmx-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.1.0/tmx_0.1.0_darwin_amd64.tar.gz"
      sha256 "1f3320b39b6e72bcc1db8dca9ae39343719835aed1768a157b24f68eab345db9"

      define_method(:install) do
        bin.install "tmx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.1.0/tmx_0.1.0_darwin_arm64.tar.gz"
      sha256 "e7a58192c9ffc2ca36d57f0ebbfd09a390552d14270994f71253138047f13105"

      define_method(:install) do
        bin.install "tmx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.1.0/tmx_0.1.0_linux_amd64.tar.gz"
      sha256 "2adb82619d66159d971e87d8a91d355b5349dd21011d1a6d8aeafeada9dac3a0"
      define_method(:install) do
        bin.install "tmx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.1.0/tmx_0.1.0_linux_arm64.tar.gz"
      sha256 "a33448284ca01eb0b19c33fd80a1f0d0c07dace6ae59a4bc80cedb79f53eb74c"
      define_method(:install) do
        bin.install "tmx"
      end
    end
  end

  test do
    system "#{bin}/tmx", "--version"
  end
end
