# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmxCli < Formula
  desc "Thermomix/Cookidoo CLI — meal plans, recipe search, and shopping lists from your terminal"
  homepage "https://github.com/aronjanosch/tmx-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.3.1/tmx_0.3.1_darwin_amd64.tar.gz"
      sha256 "e1cae6726dcc56b777b245dd6b088ca0c96c5a3438f954ad717e05a4a70adbe9"

      define_method(:install) do
        bin.install "tmx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.3.1/tmx_0.3.1_darwin_arm64.tar.gz"
      sha256 "56de086e0b09b4e3f03c7925ae8fe8e2586d91f95c0199c6ec6f000d9a4cd2d5"

      define_method(:install) do
        bin.install "tmx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.3.1/tmx_0.3.1_linux_amd64.tar.gz"
      sha256 "645c5f74abc2532f895e4b46257128826793288f9242ede3908d23c112442b34"
      define_method(:install) do
        bin.install "tmx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aronjanosch/tmx-cli/releases/download/v0.3.1/tmx_0.3.1_linux_arm64.tar.gz"
      sha256 "b780b67ca1fa45750304e23bce37d10e8fb4278f569684a0c86a1523aea31639"
      define_method(:install) do
        bin.install "tmx"
      end
    end
  end

  test do
    system "#{bin}/tmx", "--version"
  end
end
